laser_filter_node:
  ros__parameters:
    filter1:
      name: robot_body_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        max_x: 0.15
        max_y: 0.15
        max_z: 0.5
        min_x: -0.15
        min_y: -0.15
        min_z: -0.5