[env:pico]
platform = raspberrypi
board = pico
framework = arduino


board_microros_distro = jazzy
board_microros_transport = serial

platform_packages =
    platformio/toolchain-gccarmnoneeabi@~1.120301.0

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    bolderflight/Bolder Flight Systems MPU9250