[env:pico]
platform = raspberrypi
board = pico
framework = arduino

platform_packages = 
	toolchain-gccarmnoneeabi@~1.90301.0

monitor_speed = 115200

lib_deps =
    bolderflight/Bolder Flight Systems MPU9250