name: SemanticSLAM CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                submodules: recursive

            - name: Configure CMake
              run: |
                mkdir -p build
                cmake -S . -B build \
                    -DCMAKE_BUILD_TYPE=Release \
                    -DCMAKE_PREFIX_PATH=/opt/libtorch \
                    -DVCPKG_TARGET_TRIPLET=arm64-linux \
                    -DCMAKE_EXE_LINKER_FLAGS="-Wl,-rpath=/opt/libtorch/lib -Wl,-rpath-link=/opt/libtorch/lib"
            - name: Build Project
              run: cmake --build build --config Release

            - name: Deploy Executable
              run: |
                mkdir -p /home/delta/pi/SemanticSLAM/build
                cp build/slam /home/delta/pi/SemanticSLAM/build/slam
                chmod +x /home/delta/pi/SemanticSLAM/build/slam

            - name: Restart Robot Service
              run: |
                sudo systemctl restart semantic_slam